spring.application.name=back
spring.profiles.include=api

logging.level.org.springframework.messaging.simp.SimpMessagingTemplate=DEBUG
logging.level.org.springframework.web.socket=DEBUG


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB